### ISSUE TITLE
圣杯布局和双飞翼布局

### ISSUE THREAD

**Issue by lfzs** [lfzs/blog#2]
## 圣杯布局

![圣杯布局](https://user-images.githubusercontent.com/20108480/161259321-05bcd12f-4b5d-4150-a4dd-cb7d1125d61c.png)

如图，圣杯布局包含上中下三块，上下块可使用 `<header>` 和 `<footer>` 标签。接下来主要是实现中部块，使 main 宽度自适应，left 和 right 宽度固定

### 1、HTML 结构

```html
<header class="header">header</header>

<div class="container">
  <!-- 注意 main 在上面 -->
  <div class="main">main</div>
  <div class="left">left</div>
  <div class="right">right</div>
</div>

<footer class="footer">footer</footer>
```

#### 2.1、提供左右内边距给 left 和 right

```css
/* 假设 left 宽度 50px，right 宽度 100px */
.container {
  padding: 0 100px 0 50px;
}

.main {
  background-color: orange;
}

.left {
  width: 50px;
  background-color: red;
}

.right {
  width: 100px;
  background-color: blue;
}
```

![](https://user-images.githubusercontent.com/20108480/161259362-70106a1c-225c-4600-a4b4-10798d85da98.png)

#### 2.2、浮动子元素

```css
.container {
  padding: 0 100px 0 50px;
  overflow: hidden; /* 创建 BFC */
}

.container > div {
  float: left; /* 子元素浮动 */
}

.main {
  background-color: orange;
  width: 100%; /* 独占一行 */
}

.left {
  width: 50px;
  background-color: red;
}

.right {
  width: 100px;
  background-color: blue;
}
```

![](https://user-images.githubusercontent.com/20108480/161259395-daf1047b-afbc-4ba5-be08-5fab4760227e.png)

当子元素浮动之后，它会被移出正常的文档流。导致：

1、父元素 container 高度计算为 0

只需将 container 变成一个 BFC 块即可，因为 BFC 规定高度计算要包含浮动元素

2、子元素由块元素变为浮动元素，依次左对齐排列，导致 main 无法独占一行

对 main 设置 `width: 100%` 占据一行，left 和 right 换行排列

#### 2.3、利用负 margin 调整 left 和 right

```css
.container {
  padding: 0 100px 0 50px;
  overflow: hidden;
}

.container > div {
  float: left;
}

.main {
  background-color: orange;
  width: 100%;
}

.left {
  width: 50px;
  background-color: red;
  margin-left: -100%; /* 使 left 占据左边 */
}

.right {
  width: 100px;
  background-color: blue;
  margin-left: -100px; /* 使 right 占据右边  */
}
```

![](https://user-images.githubusercontent.com/20108480/161259436-d224eef9-e7c4-429a-8235-43b15edebc02.png)

left 和 right 都是有宽度的，因此利用  margin-left 进行位移调整，left 的左边刚好是宽度 100% 的 main，当 left 左位移之后，这时 right 紧贴 main，所以左位移自身宽度即可。

可以理解为 main、left 和 right 都是在一行左对齐依次排列（实际是 left 和 right 被 main 挤到换行）。

#### 2.4、相对定位调整 left 和 right

```css
.container {
  padding: 0 100px 0 50px;
  overflow: hidden;
}

.container > div {
  float: left;
  position: relative; /* 子元素相对自身定位（主要是 left 和 right） */
}

.main {
  background-color: orange;
  width: 100%;
}

.left {
  width: 50px;
  background-color: red;
  margin-left: -100%;
  left: -50px; /* 左移到最左边对齐 */
}

.right {
  width: 100px;
  background-color: blue;
  margin-left: -100px;
  right: -100px; /* 右移到最右边对齐 */
}
```

![](https://user-images.githubusercontent.com/20108480/161259473-7b80a7b8-d953-4fd1-b8ba-1ccd2334c796.png)

margin 调整无法抵消掉 padding 的影响，需要用到 `position: relative;` 定位抵消 padding 的影响

## 双飞翼布局

![双飞翼布局](https://user-images.githubusercontent.com/20108480/161259501-23e5e56e-c701-47b4-aa12-4f5376d27c61.png)

如图，双飞翼布局和圣杯布局很相似，main 宽度自适应，left 和 right 宽度固定。区别是 left 和 right 会覆盖在 main 区域上方，类似鸟的双翼，内容都被包裹在 main 内部的一个 div

### 1、HTML 结构

```html
<header class="header">header</header>

<div class="container">
  <div class="main">
    <div class="inner">inner</div>
  </div>

  <div class="left">left</div>
  <div class="right">right</div>
</div>

<footer class="footer">footer</footer>
```

#### 2.1 浮动元素

```css
/* 假设 left 宽度 50px，right 宽度 100px */
.container {
  overflow: hidden; /* 创建 BFC 块，包裹内部浮动元素 */
}

.container > div {
  float: left;
}

.main {
  width: 100%; /* 中间宽度占满 */
  background-color: orange;
}

.left {
  width: 50px;
  background-color: red;
}

.right {
  width: 100px;
  background-color: blue;
}
```

![](https://user-images.githubusercontent.com/20108480/161259536-20640b64-36cb-4b49-8f59-cb9c166f353b.png)

#### 2.2 定位

```css
.container {
  overflow: hidden;
}

.container > div {
  float: left;
}

.main {
  width: 100%;
  background-color: orange;
}

.main .inner {
  margin: 0 100px 0 50px; /* 中间内部内容留出左右边距，避免被 left 和 right 遮盖 */
}

.left {
  width: 50px;
  background-color: red;
  margin-left: -100%; /* 左移到最左边对齐 */
}

.right {
  width: 100px;
  background-color: blue;
  margin-left: -100px; /* 右移到最右边对齐 */
}
```

![](https://user-images.githubusercontent.com/20108480/161259575-3cd774f2-13e9-4895-ad2b-74348c4fba5e.png)

## 总结

虽然现在 flex、grid 布局已大行其道吗，但是掌握圣杯布局和双飞翼布局对理解 BFC、float、负 margin 等技术还是很有必要的
